services:
  ssh-host:
    build:
      dockerfile: service.Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ../:/code
networks:
  default:
    external: true
    name: my-postgres_default
